### ISSUE TITLE
query about "def padMatrix"

### ISSUE THREAD

**Issue by jeaninesong** [mp2893/gram#4]
Hi! I wonder that what is the definition of "mask" in function def padMatrix(...)?

Looking for your kind reply, thanks very much!

**Comment by mp2893** [comment]
Hi Jeanine,

Mask variable is for masking the predictions occurring at the padded elements, so there won't be any parameter updates caused by the padded elements.
(Each patient has different number of visits, so that's why you need to pad the ones with fewer number of visits to build a minibatch)
These are engineering/implementation tricks you might want to learn from Tensorflow tutorials.

Thanks,
Ed

**Comment by jeaninesong** [comment]
ok, thanks very much!
